### ISSUE TITLE
Can't specify multiple files

### ISSUE THREAD

**Issue by victor-david** [Canop/rhit#14]
My log directory has files from different sub domains
- default.access.log
- user.access.log
- etc

I don't want all of them combined. I want to see one sub domain at a time.

This works fine if there's only one file for a particular subdomain.

~~~
rhit default.access.log
~~~

But (after log rollover) there's multiple files for the same sub domain

- default.access.log
- default.access.log.1
- etc.

I can do one at a time, no problem, but I want a combined view of a single sub domain. I tried:

~~~
rhit default.access*
~~~

but I get _Unrecognized argument: default.access.log.1_

So it seems **rhit** is finding the other file but is not treating it as a file to read, but rather like some other argument.

Any ideas? Thanks

**Comment by Canop** [comment]
I'm not sure I understand what you want. You'd want all the tables for the first file, then all the tables for the second file ?

**Comment by victor-david** [comment]
If I do _rhit_  (no args) in the log directory, it gathers and combines info from all files, figures out the dates, paths, bytes, etc. across all of the files. However, this isn't what I want. I don't want to combine all sub domains into a single report.

If I do _rhit default.access.log_, it gathers info from a single file. 

What I want is to gather and combine info from all files that start with (for instance) _default.access_, hence the _rhit default.access*_ that I tried.

I could configure nginx to put logs for different sub domains into separate sub directories, but I was hoping to find a way to do it when all logs are in a single directory.

Since you can specify a file, I thought I could specify multiple files using a wildcard.

**Comment by Canop** [comment]
OK, I get it.
I'll see what I can do for that.

**Comment by victor-david** [comment]
Thanks. By the way, I forgot to mention that I'm using v 1.6.0 which seems to be the latest version. I downloaded it directly from your web site.
