### ISSUE TITLE
Whether to support minute-dimension traffic statistics

### ISSUE THREAD

**Issue by xiangbinwu-allen** [Canop/rhit#18]
We count the request demand in the minute dimension,
Would like to ask whether our tool supports this function.

Looking forward to your reply.

**Comment by Canop** [comment]
What would you do with the minutes ? What kind of display/statistics are you expecting ?

**Comment by xiangbinwu-allen** [comment]
![image](https://user-images.githubusercontent.com/52592063/169751013-f8145220-37b9-46a3-9645-fd469b009dd8.png)
![image](https://user-images.githubusercontent.com/52592063/169752171-153fc3e8-d073-4a22-9d1c-5cb942a04d35.png)
The picture 1 : our server TCP connection monitoring, from zabbix.
The picture 2: referrer and path  is already kindly for us.
why we do with the minutes ? 
         We found that there is an abnormal connection between 2:20 ~ 2:27
         We hope to use rhit to display  the number of requests grouped based on source ip  or request url  in this range

**Comment by Canop** [comment]
OK.
There's no such feature today but I'll probably add precise time ranging in a near future.

**Comment by Canop** [comment]
There's a branch with the feature: https://github.com/Canop/rhit/pull/29

Tests would be appreciated as it's a deep change
