### ISSUE TITLE
`cargo install rhit` fails with E0659

### ISSUE THREAD

**Issue by V0ldek** [Canop/rhit#22]
When installing from `cargo` I get the following error:
![image](https://user-images.githubusercontent.com/20441980/221426851-b1cfd9ce-12a5-4425-9321-da26ac8734b1.png)

This is for latest 1.7.1.

Running with stable rust 1.67.1 on Ubuntu 20.04.5 LTS.

**Comment by Canop** [comment]
Can you try install rhit with `cargo install --locked rhit` ?

**Comment by V0ldek** [comment]
That works, thank you.
