### ISSUE TITLE
Add arm64 and arm32 binaries on release

### ISSUE THREAD

**Issue by patrickelectric** [Canop/rhit#24]

**Comment by Canop** [comment]
What [platforms](https://github.com/cross-rs/cross#supported-targets) are you interested into ? You want to run rhit on what kind of system ?

**Comment by patrickelectric** [comment]
Raspberry Pi 3 and 4. We are working in an image and would like to add your software as one of the available tools on the system by default.

**Comment by Canop** [comment]
For arm32, `armv7-unknown-linux-gnueabihf` should be OK. I've put it here for verification: https://dystroy.org/rhit/download/

I'm not sure there's a ready to use image for arm64 but I don't really know the Raspberry world.

**Comment by mrjackwills** [comment]
> For arm32, `armv7-unknown-linux-gnueabihf` should be OK. I've put it here for verification: https://dystroy.org/rhit/download/
> 
> I'm not sure there's a ready to use image for arm64 but I don't really know the Raspberry world.

`aarch64-unknown-linux-gnu` for 64 bit Raspberry Pi.

I built using `cross build --target aarch64-unknown-linux-gnu --release`, and it worked perfectly on my pi 4 running 64bit piOS.

**Comment by Canop** [comment]
Unless you see a problem, I'll merge this: https://github.com/Canop/rhit/pull/27

**Comment by mrjackwills** [comment]
It's possible to build for 32 but arm with musl as well. I only suggested musl targets because I've had issues, with other projects, in the past where the GCC (I think) version on the build machine didn't match with the target machine, and then the cross compiled binary won't work on the pi. 

But maybe the cross docker image handles this better than building using cargo and any installed targets.

**Comment by Canop** [comment]
I already build for MUSL for x86 because those problems exist. I guess I can do it for arm32 too.

**Comment by mrjackwills** [comment]
Currently away from computers, but next week I can build and run on real hardware, both 32 and 64 bit arm pi's, but can't see any reason why it won't work

**Comment by mrjackwills** [comment]
Yup, can confirm, works on real hardware.

For Pi4 64Bit pi OS:
```cross build --target aarch64-unknown-linux-musl --release```

and for pi zero W 32bit pi OS:
```cross build --target arm-unknown-linux-musleabihf --release```
