### ISSUE TITLE
Distribute binary releases on PyPI

### ISSUE THREAD

**Issue by messense** [Canop/rhit#5]
I've recently added distribution of binary release on [PyPI](https://pypi.org/project/roapi-http/#files) for [roapi](https://github.com/roapi/roapi/pull/25/files), I was wondering if you'd like to distribute rhit on PyPI. I can provide PR if it's OK.

It will be easy to install rhit binary with pip which exists on most well known operating systems: `pip install rhit`.

**Comment by Canop** [comment]
Thanks.

I'm not familiar with PyPi as a publisher, or for binary releases.

How is handled the packaging of different binaries per target (OS, CPU, etc.) ? There's already a Musl version and I might make a Windows one if users ask for it.

**Comment by messense** [comment]
For Linux we have [manylinx](https://github.com/pypa/manylinux) specification which supports x86_64/i686/aarch64/armv7l/s390x CPUs, macOS and Windows support x86_64 and aarch64 wheels.

**Comment by messense** [comment]
You can take a look at https://pypi.org/project/roapi-http/#files to see the different binaries per target .

**Comment by Canop** [comment]
If you make a PR with the packaging thingies I'll have a look and register rhit on pypi and propose it to users if I see no problem.

In any case the idea is welcome.
