### ISSUE TITLE
Homebrew support and request github release

### ISSUE THREAD

**Issue by chenrui333** [Canop/rhit#9]
👋  we have a pending PR of including this utility into the homebrew-core, it would be great that we can do some github release managements, so that the downstream packaging would be beneficial from it. Thanks!

relates to:
- https://github.com/Homebrew/homebrew-core/pull/81076

**Comment by Canop** [comment]
Would you be OK with the releases pattern I follow for [broot](https://github.com/Canop/broot/releases) ?

**Comment by vladimyr** [comment]
> Would you be OK with the releases pattern I follow for [broot](https://github.com/Canop/broot/releases) ?

Sure, that would be great! 👍

**Comment by chenrui333** [comment]
@Canop totally works for me, thanks!!

**Comment by Canop** [comment]
Done. I'll let you close this issue when (and if) you confirm it's OK.

For the record, I didn't publish releases because nobody ever told me to be using rhit... there was no point if I was the sole user.

**Comment by vladimyr** [comment]
> Done. I'll let you close this issue when (and if) you confirm it's OK.

Thank you! I've successfully compiled it locally and verified it is working correctly. 👍  Right now I'm waiting for the green light from Homebrew's CI.

> For the record, I didn't publish releases because nobody ever told me to be using rhit... there was no point if I was the sole user.

Who doesn't like good software 😄

**Comment by chenrui333** [comment]
```
$ brew install rhit
==> Downloading https://ghcr.io/v2/homebrew/core/rhit/manifests/1.5.3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/rhit/blobs/sha256:b0da544cfff128f8f762
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:b0
######################################################################## 100.0%
==> Pouring rhit--1.5.3.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/rhit/1.5.3: 8 files, 1.7MB
```
🍺  🍺

**Comment by Canop** [comment]
It's now mentioned in the install page: https://dystroy.org/rhit/install/#homebrew
